project:
  type: website

website:
  title: "Intermediate R"
  page-navigation: true

  sidebar: 
    title: "Intermediate R"
    logo: "assets/UoB_RGB_24.png"
    align: center
    logo-alt: "University of Bristol logo"
    style: "docked"
    border: true
    contents: 
      - "index.qmd"
      - "pages/010-workspace-setup.qmd"
      - section: "pages/020-packages.qmd"
        contents:
          - "pages/021-install-packages.qmd"
          - "pages/022-loading-packages.qmd"
      - section: "pages/030-functions.qmd"
        contents:
          - "pages/031-importing-functions.qmd"
          - "pages/032-writing-functions.qmd"
      - section: "pages/040-tidyverse.qmd"
        contents:
          - "pages/041-tidyverse-tibbles.qmd"
          - "pages/042-tidyverse-pipe.qmd"
          - "pages/043-tidyverse-exercise.qmd"
      - "pages/070-worksheet.qmd"
      - "pages/980-summary.qmd"
      - "pages/990-contributors.qmd"


  page-footer:
    left: "[Jean Golding Institute](https://www.bristol.ac.uk/golding/) © [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"  
  repo-url: https://github.com/uob-training/intermediate-r
#  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    shift-heading-level-by: 1
    highlight-style: github

    # code-line-numbers: true

execute:
  freeze: auto
  error: true

